apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: workshop
spec:
  selector:
    app: voter
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: voter-svc
  namespace: workshop
spec:
  type: NodePort
  selector:
    app: voter
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: result-svc
  namespace: workshop
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31001
